version: '3.3'
services:
  mototale:
         image: vishalphopalkar/dockerpractice:v1

 nginx:
         image: nginx:latest

         volumes:
                ./conf.d:/etc/nginx/conf.d
         depends_on: mototale

         ports:
              9099:80

